---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Posts
- type: directory
  path: src/data
  label: Users
  create: all
  match: "**/*"
- type: directory
  path: src/pages
  label: 'Static '
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: src/pages/blog
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: md
- type: document
  path: uploads
  label: Documents
upload_dir: uploads
public_path: "/public/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
